version: "3.9"
services:
  db:
    image: mysql:8.0
    container_name: "hibernate_sandbox_db"
    ports:
      - "33306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hibernate_sandbox
