spring:
  datasource:
    url: jdbc:mysql://localhost:33306/hibernate_sandbox
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        generate_statistics: true
        session.events.log:
          LOG_QUERIES_SLOWER_THAN_MS: 1
